version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: cimg/node:14.18.0
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  checkout:
    executor: node-executor
    steps:
      - *attach_workspace
      - checkout
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  install-dependencies-apps-script:
    executor: node-executor
    working_directory: ~/project/google-scripts
    steps:
      - *attach_workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  unit-tests-apps-script:
    executor: node-executor
    working_directory: ~/project/google-scripts
    steps:
      - *attach_workspace
      - run:
          name: Run typecheck
          command: yarn tsc --noEmit
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
    environment:
      TZ: "Europe/London"

  clasp-push:
    executor: node-executor
    working_directory: ~/project/google-scripts
    steps:
      - *attach_workspace
      - run:
          name: create clasprc.json file in root
          command: |
            echo "{\"token\":{\"scope\":\"https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly\",\"token_type\":\"bearer\",\"refresh_token\":\"$CLASP_REFRESH_TOKEN\",\"access_token\":\"\"}}" > ~/.clasprc.json
      - run:
          name: create appsscript.json file
          command: |
            echo "{\"timeZone\": \"Europe\/London\",\"dependencies\": {},\"exceptionLogging\": \"STACKDRIVER\",\"runtimeVersion\": \"V8\"}" > ~/project/google-scripts/process-form-submission/appsscript.json
      - run:
          name: Clasp push
          command: ./node_modules/@google/clasp/build/src/index.js push --force

  terraform-init-then-apply-to-staging:
    executor: docker-terraform
    description: "Initializes and applies terraform configuration for AWS MASH Resources"
    working_directory: ~/project/terraform/mash-setup-staging
    steps:
      - *attach_workspace
      - run:
          name: get and init
          command: |
            terraform get -update=true
            terraform init -backend-config="bucket=terraform-state-staging-apis" -backend-config="region=eu-west-2" -backend-config="key=social-care-referrals/staging-terraform.tfstate" -backend-config="encrypt=true"
      - run:
          name: apply
          command: |
            terraform apply -auto-approve

  assume-role-staging:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_STAGING
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  assume-role-mosaic-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_PRODUCTION
          profile_name: default
          role: "circleci-assume-role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  install-dependencies-lambda:
    executor: node-executor
    working_directory: ~/project/referral-form-data-process
    steps:
      - *attach_workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  unit-tests-lambda:
    executor: node-executor
    working_directory: ~/project/referral-form-data-process
    steps:
      - *attach_workspace
      - run:
          name: Run typecheck
          command: yarn tsc --noEmit
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test --runInBand
    environment:
      TZ: "Europe/London"

  compile-lambda:
    executor: node-executor
    working_directory: ~/project/referral-form-data-process
    steps:
      - *attach_workspace
      - run:
          name: Compile Lambda
          command: yarn tsc main.ts
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  deploy-lambda:
    executor: node-executor
    working_directory: ~/project/referral-form-data-process
    steps:
      - *attach_workspace
      - run:
          name: "deploy"
          command: "yarn deploy -s mosaic-prod --CLIENT_EMAIL $CLIENT_EMAIL --PRIVATE_KEY $PRIVATE_KEY --TEMPLATE_DOCUMENT_ID $TEMPLATE_DOCUMENT_ID --TITLE $TITLE --URL_COLUMN $URL_COLUMN --SPREADSHEET_ID $SPREADSHEET_ID"

workflows:
  version: 2
  process-form-submission:
    jobs:
      - checkout
      - install-dependencies-apps-script:
          requires:
            - checkout
      - unit-tests-apps-script:
          requires:
            - install-dependencies-apps-script
      - clasp-push:
          requires:
            - unit-tests-apps-script
          filters:
            branches:
              only: main
      - assume-role-staging:
          context: api-assume-role-staging-context
          requires:
            - checkout
          filters:
            branches:
              only: main
      - terraform-init-then-apply-to-staging:
          requires:
            - assume-role-staging
          filters:
            branches:
              only: main
      - install-dependencies-lambda:
          requires:
            - checkout
      - unit-tests-lambda:
          requires:
            - install-dependencies-lambda
      - permit-deploy-production:
          type: approval
          requires:
            - unit-tests-lambda
          filters:
            branches:
              only: main
      - assume-role-mosaic-production:
          context: api-assume-role-social-care-production-context
          requires:
            - permit-deploy-production
          filters:
            branches:
              only: main
      - compile-lambda:
          requires:
            - assume-role-mosaic-production
          filters:
            branches:
              only: main
      - deploy-lambda:
          requires:
            - compile-lambda
          filters:
            branches:
              only: main
