service: referral-form-data-process

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  lambdaHashingVersion: 20201221
  timeout: 30
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "social-care-referrals-bucket"
                - "/*"

functions:
  main:
    environment:
      CLIENTEMAIL: ${opt:CLIENTEMAIL}
      PRIVATEKEY: ${opt:PRIVATEKEY}
      TEMPLATEDOCUMENTID: ${opt:TEMPLATEDOCUMENTID}
      TITLE: ${opt:TITLE}
    handler: referral-form-data-process/main.handler
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "social-care-referrals-queue"
