service: referral-form-data-process

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  lambdaHashingVersion: 20201221

functions:
  main:
    environment:
      CLIENT_EMAIL: ${opt:CLIENT_EMAIL}
      PRIVATE_KEY: ${opt:PRIVATE_KEY}
    handler: handler.main
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "social-care-referrals-queue"
