service: referral-form-data-process

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "social-care-referrals-bucket"
                - "/*"

functions:
  main:
    environment:
      CLIENT_EMAIL: ${opt:CLIENT_EMAIL}
      PRIVATE_KEY: ${opt:PRIVATE_KEY}
      TEMPLATE_DOCUMENT_ID: ${opt:TEMPLATE_DOCUMENT_ID}
      TITLE: ${opt:TITLE}
    handler: referral-form-data-process/main.handler
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "social-care-referrals-queue"
