service: referral-form-data-process

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: "arn:aws:s3:::${self:custom.referralsBucket}/*"

functions:
  main:
    name: ${self:service}-${self:provider.stage}
    handler: referral-form-data-process/main.handler
    environment:
      CLIENT_EMAIL: ${opt:CLIENT_EMAIL}
      PRIVATE_KEY: ${opt:PRIVATE_KEY}
      TEMPLATE_DOCUMENT_ID: ${opt:TEMPLATE_DOCUMENT_ID}
      TITLE: ${opt:TITLE}
      URL_COLUMN: ${opt:URL_COLUMN}
      SPREADSHEET_ID: ${opt:SPREADSHEET_ID}
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "${self:custom.referralsQueue}"

custom:
  referralsBucket:
    staging: social-care-referrals-stg-bucket
    mosaic-prod: social-care-referrals-bucket
  referralsQueue:
    staging: social-care-referrals-stg-queue
    mosaic-prod: social-care-referrals-queue
