service: referral-form-data-process

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: "arn:aws:s3:::${self:custom.referralsBucket.${opt:stage}}/*"

functions:
  main:
    name: ${self:service}-${self:provider.stage}
    handler: referral-form-data-process/main.handler
    environment:
      CLIENT_EMAIL: ${ssm:/aws/reference/secretsmanager/social-care-referrals-${self:custom.environmentTag.${opt:stage}}-gcp-service-account-client-email~true}
      PRIVATE_KEY: ${ssm:/aws/reference/secretsmanager/social-care-referrals-${self:custom.environmentTag.${opt:stage}}-gcp-service-account-private-key~true}
      TEMPLATE_DOCUMENT_ID: ${ssm:/aws/reference/secretsmanager/social-care-referrals-${self:custom.environmentTag.${opt:stage}}-referrals-google-doc-template-id~true}
      SPREADSHEET_ID: ${ssm:/aws/reference/secretsmanager/social-care-referrals-${self:custom.environmentTag.${opt:stage}}-referrals-google-spreadsheet-id~true}
      ITLE: ${opt:TITLE}
      URL_COLUMN: ${opt:URL_COLUMN}
    events:
      - sqs:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sqs"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "${self:custom.referralsQueue.${opt:stage}}"

custom:
  referralsBucket:
    staging: social-care-referrals-stg-bucket
    mosaic-prod: social-care-referrals-bucket
  referralsQueue:
    staging: social-care-referrals-stg-queue
    mosaic-prod: social-care-referrals-queue
  environmentTag:
    staging: stg
    mosaic-prod: prod
