export interface FormDataAnswersObject {
  referrerFirstName: string | undefined;
  referrerLastName: string | undefined;
  clientOneFirstName: string | undefined;
  clientOneLastName: string | undefined;
  clientTwoFirstName: string | undefined;
  clientTwoLastName: string | undefined;
  clientThreeFirstName: string | undefined;
  clientThreeLastName: string | undefined;
  clientFourFirstName: string | undefined;
  clientFourLastName: string | undefined;
  clientFiveFirstName: string | undefined;
  clientFiveLastName: string | undefined;
  clientSixFirstName: string | undefined;
  clientSixLastName: string | undefined;
  clientSevenFirstName: string | undefined;
  clientSevenLastName: string | undefined;
  clientEightFirstName: string | undefined;
  clientEightLastName: string | undefined;
  requestedSupport: string | undefined;
}
